Repository KWcapstone/server, pull requests merged in 2025-03, with the labels that each got.

#28 [Refactor] security config 및 jwtrequestfilter 수정
  src/main/java/com/kwcapstone/Exception/AuthenticationException.java
  src/main/java/com/kwcapstone/Exception/BadRequestException.java
  src/main/java/com/kwcapstone/Exception/BaseException.java
  src/main/java/com/kwcapstone/Kakao/Service/KakaoService.java
  src/main/java/com/kwcapstone/Repository/MemberRepository.java
  src/main/java/com/kwcapstone/Security/JwtRequestFilter.java
  src/main/java/com/kwcapstone/Security/PrincipalDetails.java
  src/main/java/com/kwcapstone/Security/PrincipalDetailsService.java
Labels: feature, refactor

#36 [Refactor] Jwt 발급 방식 변경
  src/main/java/com/kwcapstone/Kakao/Service/KaKaoProvider.java
  src/main/java/com/kwcapstone/Kakao/Service/KakaoService.java
  src/main/java/com/kwcapstone/Repository/MemberRepository.java
  src/main/java/com/kwcapstone/Security/JwtRequestFilter.java
  src/main/java/com/kwcapstone/Security/PrincipalDetailsService.java
  src/main/java/com/kwcapstone/Service/MemberService.java
  src/main/java/com/kwcapstone/Token/JwtTokenProvider.java
  src/main/java/com/kwcapstone/Token/Service/TokenService.java
  src/main/resources/application.properties
Labels: refactor

#38 35 refactor 로그아웃 수정하겠습니다
  src/main/java/com/kwcapstone/Config/SecurityConfig.java
  src/main/java/com/kwcapstone/Service/MemberService.java
  src/main/java/com/kwcapstone/Token/Service/TokenService.java
  src/main/resources/application.properties
Labels: refactor

#40 [Refactor] kakao Login token 오류 고치기
  src/main/java/com/kwcapstone/Common/BaseResponse.java
  src/main/java/com/kwcapstone/Common/code/BaseCode.java
  src/main/java/com/kwcapstone/Common/code/ResponseDTO.java
  src/main/java/com/kwcapstone/Common/code/SuccessStatus.java
  src/main/java/com/kwcapstone/Kakao/Service/KakaoService.java
  src/main/java/com/kwcapstone/Service/GoogleOAuthService.java
Labels: refactor

#42 39 refactor 구글 로그인 메서드 수정하겠습니다
  src/main/java/com/kwcapstone/Config/SecurityConfig.java
  src/main/java/com/kwcapstone/Controller/MemberController.java
  src/main/java/com/kwcapstone/Security/JwtRequestFilter.java
  src/main/java/com/kwcapstone/Service/MemberService.java
Labels: refactor

#43 [Refactor] Success Enum 추가 및 ResponseDto MemberId String 타입으로 변경
  src/main/java/com/kwcapstone/Common/BaseResponse.java
  src/main/java/com/kwcapstone/Common/code/BaseCode.java
  src/main/java/com/kwcapstone/Common/code/ResponseDTO.java
  src/main/java/com/kwcapstone/Common/code/SuccessStatus.java
  src/main/java/com/kwcapstone/Controller/MemberController.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/MemberLoginResponseDto.java
  src/main/java/com/kwcapstone/Domain/Entity/Member.java
  src/main/java/com/kwcapstone/Kakao/Controller/KakaoController.java
  src/main/java/com/kwcapstone/Kakao/Dto/KakaoResponse.java
  src/main/java/com/kwcapstone/Kakao/Service/KaKaoProvider.java
  src/main/java/com/kwcapstone/Kakao/Service/KakaoService.java
  src/main/java/com/kwcapstone/Service/MemberService.java
  src/main/java/com/kwcapstone/Token/Controller/TokenController.java
  src/main/java/com/kwcapstone/Token/JwtTokenProvider.java
Labels: refactor

#50 Feat: 알림창 세부 조회 기능 구현
  src/main/java/com/kwcapstone/Common/code/SuccessStatus.java
  src/main/java/com/kwcapstone/Controller/MainController.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/NoticeDetailReadResponseDto.java
  src/main/java/com/kwcapstone/Domain/Entity/Notice.java
  src/main/java/com/kwcapstone/Service/MainService.java
Labels: feature

#58 [Feat] 회원 탈퇴 구현
  src/main/java/com/kwcapstone/Common/BaseErrorResponse.java
  src/main/java/com/kwcapstone/Common/code/SuccessStatus.java
  src/main/java/com/kwcapstone/Controller/MemberController.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/GoogleTokenResponseDto.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/MemberLoginResponseDto.java
  src/main/java/com/kwcapstone/Domain/Entity/MemberToProject.java
  src/main/java/com/kwcapstone/Domain/Entity/Project.java
  src/main/java/com/kwcapstone/Kakao/Dto/KakaoResponse.java
  src/main/java/com/kwcapstone/Kakao/Service/KaKaoProvider.java
  src/main/java/com/kwcapstone/Kakao/Service/KakaoService.java
  src/main/java/com/kwcapstone/Naver/Dto/NaverResponse.java
  src/main/java/com/kwcapstone/Naver/Service/NaverProvider.java
  src/main/java/com/kwcapstone/Naver/Service/NaverService.java
  src/main/java/com/kwcapstone/Repository/MemberRepository.java
  src/main/java/com/kwcapstone/Security/JwtRequestFilter.java
  src/main/java/com/kwcapstone/Security/PrincipalDetails.java
  src/main/java/com/kwcapstone/Service/GoogleOAuthService.java
  src/main/java/com/kwcapstone/Service/MemberService.java
  src/main/java/com/kwcapstone/Token/Controller/TokenController.java
  src/main/java/com/kwcapstone/Token/Domain/Dto/TokenRequest.java
  src/main/java/com/kwcapstone/Token/Domain/Token.java
  src/main/java/com/kwcapstone/Token/JwtTokenProvider.java
  src/main/java/com/kwcapstone/Token/Repository/TokenRepository.java
  src/main/java/com/kwcapstone/Token/Service/TokenService.java
Labels: feature

#60 [Refactor] 파일 위치 변경
  src/main/java/com/kwcapstone/Common/Response/BaseCode.java
  src/main/java/com/kwcapstone/Common/Response/BaseErrorResponse.java
  src/main/java/com/kwcapstone/Common/Response/BaseResponse.java
  src/main/java/com/kwcapstone/Common/Response/ResponseDTO.java
  src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java
  src/main/java/com/kwcapstone/Controller/MainController.java
  src/main/java/com/kwcapstone/Controller/MemberController.java
  src/main/java/com/kwcapstone/Kakao/Controller/KakaoController.java
  src/main/java/com/kwcapstone/Naver/Controller/NaverController.java
  src/main/java/com/kwcapstone/Service/GoogleOAuthService.java
  src/main/java/com/kwcapstone/Service/MemberService.java
  src/main/java/com/kwcapstone/Token/Controller/TokenController.java
Labels: refactor

#62 Feat/57 메인화면 검색 기능 만들겠습니다
  src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java
  src/main/java/com/kwcapstone/Controller/MainController.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/SearchResponseWrapperDto.java
  src/main/java/com/kwcapstone/Domain/Entity/Project.java
  src/main/java/com/kwcapstone/Service/GoogleOAuthService.java
  src/main/java/com/kwcapstone/Service/MainService.java
  src/main/java/com/kwcapstone/Service/MemberService.java
Labels: feature

#64 Feat: 모든 회의 메인화면 기능 구현
  src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java
  src/main/java/com/kwcapstone/Controller/MainController.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/ShowMainResponseDto.java
  src/main/java/com/kwcapstone/Service/MainService.java
Labels: feature

#66 Feat: 요약본 메인화면 기능 구현
  src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java
  src/main/java/com/kwcapstone/Controller/MainController.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/ShowSummaryResponseDto.java
  src/main/java/com/kwcapstone/Service/MainService.java
Labels: feature

#68 [Feat] 비밀번호 변경
  src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java
  src/main/java/com/kwcapstone/Controller/MainController.java
  src/main/java/com/kwcapstone/Controller/MemberController.java
  src/main/java/com/kwcapstone/Domain/Dto/Request/PasswordRequestDto.java
  src/main/java/com/kwcapstone/Domain/Entity/Member.java
  src/main/java/com/kwcapstone/Security/JwtRequestFilter.java
  src/main/java/com/kwcapstone/Service/MemberService.java
Labels: feature

#71 [Feat] 프로필 모달
  src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java
  src/main/java/com/kwcapstone/Controller/MainController.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/ProfileResponseDto.java
  src/main/java/com/kwcapstone/Service/MainService.java
  src/main/java/com/kwcapstone/Service/MemberService.java
Labels: feature
