Repository KWcapstone/server, pull requests merged in 2025-05, with the labels that each got.

#116 [Feat] STOMP websocket config 추가하기
  build.gradle
  src/main/java/com/kwcapstone/Config/WebSocketConfig.java
  src/main/java/com/kwcapstone/Token/Service/TokenService.java
Labels: feature

#118 [Fix] jwt 토큰 만료 상태 코드 불일치해결
  src/main/java/com/kwcapstone/Security/JwtRequestFilter.java
Labels: fix

#119 [Fix] accessToken 유효성 message 수정
  src/main/java/com/kwcapstone/Security/JwtRequestFilter.java
  src/main/java/com/kwcapstone/Token/JwtTokenProvider.java
Labels: fix

#124 [Fix] security environment 수정
  src/main/java/com/kwcapstone/Naver/Service/NaverService.java
  src/main/java/com/kwcapstone/Token/JwtTokenProvider.java
Labels: fix

#130 [FIX] projectid 를 string 타입으로 change
  src/main/java/com/kwcapstone/Config/WebSocketConfig.java
  src/main/java/com/kwcapstone/Controller/ProjectController.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/InviteUsersByLinkResponseDto.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/ProjectNameEditResponseDto.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/SearchResponseWrapperDto.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/ShowMainResponseDto.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/ShowRecordResponseDto.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/ShowSummaryResponseDto.java
  src/main/java/com/kwcapstone/KwcapstoneApplication.java
  src/main/java/com/kwcapstone/Repository/ProjectRepository.java
  src/main/java/com/kwcapstone/Service/MainService.java
  src/main/java/com/kwcapstone/Service/MemberService.java
  src/main/java/com/kwcapstone/Service/ProjectService.java
Labels: fix

#133 [FIX] filter 수정
  src/main/java/com/kwcapstone/Controller/MainController.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/ProjectNameEditResponseDto.java
  src/main/java/com/kwcapstone/Service/MainService.java
Labels: fix

#146 [Feat] webscocket과 jwt 연결
  src/main/java/com/kwcapstone/Config/JwtHandShakeInterceptor.java
  src/main/java/com/kwcapstone/Config/WebSocketConfig.java
Labels: feature

#150 Restore from 148
  .github/workflows/gradle.yml
  src/main/java/com/kwcapstone/Config/RoomParticipantTracker.java
  src/main/java/com/kwcapstone/Config/WebSocketConfig.java
  src/main/java/com/kwcapstone/Config/WebSocketEventListener.java
  src/main/java/com/kwcapstone/Config/WebSocketSessionRegistry.java
  src/main/java/com/kwcapstone/Controller/ConferenceController.java
  src/main/java/com/kwcapstone/Controller/WebSocketController.java
  src/main/java/com/kwcapstone/Domain/Dto/Request/ParticipantRequestDto.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/ParticipantResponseDto.java
Labels: feature

#151 Refactor: 참여자 수/이름 업데이트 수정
  src/main/java/com/kwcapstone/Config/RoomParticipantTracker.java
  src/main/java/com/kwcapstone/Config/WebSocketEventListener.java
  src/main/java/com/kwcapstone/Controller/WebSocketController.java
  src/main/java/com/kwcapstone/Domain/Dto/Request/ParticipantDto.java
  src/main/java/com/kwcapstone/Domain/Dto/Request/ParticipantEventDto.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/ParticipantResponseDto.java
Labels: refactor

#153 Refactor: 사용자 초대 기능, 초대 수락 기능 수정
  src/main/java/com/kwcapstone/Controller/ProjectController.java
  src/main/java/com/kwcapstone/Service/ProjectService.java
Labels: refactor

#154 [Feat] 실시간 요약 만들기
  build.gradle
  src/main/java/com/kwcapstone/AI/GptConfig.java
  src/main/java/com/kwcapstone/AI/GptController.java
  src/main/java/com/kwcapstone/AI/GptDto.java
  src/main/java/com/kwcapstone/AI/GptService.java
  src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java
  src/main/java/com/kwcapstone/Config/JwtHandShakeInterceptor.java
  src/main/java/com/kwcapstone/Config/SecurityConfig.java
  src/main/java/com/kwcapstone/Config/WebClientConfig.java
  src/main/java/com/kwcapstone/Config/WebSocketConfig.java
  src/main/java/com/kwcapstone/Controller/WebSocketController.java
  src/main/java/com/kwcapstone/Service/WebSocketService.java
Labels: feature

#156 [Refactor] invite url 변경하기
  src/main/java/com/kwcapstone/Service/ProjectService.java
Labels: refactor

#158 Feat/147 추천 키워드 기능 만들겠습니다
  src/main/java/com/kwcapstone/AI/GptService.java
  src/main/java/com/kwcapstone/Controller/MainController.java
  src/main/java/com/kwcapstone/Controller/WebSocketController.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/NewProjectResponseDto.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/RecommendKeywordDto.java
  src/main/java/com/kwcapstone/Service/ConferenceService.java
  src/main/java/com/kwcapstone/Service/WebSocketService.java
Labels: refactor

#160 [Refactor] 공유 모달 url 고치기
  src/main/java/com/kwcapstone/Service/ProjectService.java
Labels: refactor

#161 [Refactor] 주요 키워드 5개 띄우기
  src/main/java/com/kwcapstone/AI/GptController.java
  src/main/java/com/kwcapstone/AI/GptService.java
  src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java
  src/main/java/com/kwcapstone/Service/WebSocketService.java
Labels: feature

#165 Feat/147 추천 키워드 기능 만들겠습니다
  .gitignore
  src/main/java/com/kwcapstone/AI/GptController.java
  src/main/java/com/kwcapstone/AI/GptService.java
  src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java
  src/main/java/com/kwcapstone/Controller/WebSocketController.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/RecommendKeywordDto.java
  src/main/java/com/kwcapstone/Security/JwtRequestFilter.java
  src/main/java/com/kwcapstone/Service/WebSocketService.java
  tmp/script_681314e271d72cd0218ac7fb.txt
Labels: feature

#167 Feat/147 추천 키워드 기능 만들겠습니다
  src/main/java/com/kwcapstone/Config/RoomParticipantTracker.java
  src/main/java/com/kwcapstone/Config/WebSocketEventListener.java
  src/main/java/com/kwcapstone/Controller/WebSocketController.java
  src/main/java/com/kwcapstone/Domain/Dto/Request/ParticipantDto.java
  src/main/java/com/kwcapstone/Domain/Dto/Request/ParticipantEventDto.java
  src/main/java/com/kwcapstone/Security/JwtRequestFilter.java
Labels: refactor

#166 [Feat] 회의 마인드맵 업데이트 설정
  src/main/java/com/kwcapstone/Domain/Dto/Response/DataDto.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/NodeDto.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/NodeUpdateResponseDto.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/PositionDto.java
  src/main/java/com/kwcapstone/Domain/Entity/Node.java
  src/main/java/com/kwcapstone/Repository/NodeRepository.java
  src/main/java/com/kwcapstone/Security/JwtRequestFilter.java
Labels: feature

#168 Feat/147 추천 키워드 기능 만들겠습니다
  src/main/java/com/kwcapstone/Domain/Dto/Response/NewProjectResponseDto.java
  src/main/java/com/kwcapstone/Repository/ProjectRepository.java
  src/main/java/com/kwcapstone/Service/ConferenceService.java
  src/main/java/com/kwcapstone/Service/ProjectService.java
Labels: refactor

#171 Refactor: 도커 수정
  .github/workflows/gradle.yml
Labels: refactor

#172 [Feat] 비번 동일한지 확인하기
  src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java
  src/main/java/com/kwcapstone/Controller/MemberController.java
  src/main/java/com/kwcapstone/Domain/Dto/Request/AuthPasswordCheckingRequestDto.java
  src/main/java/com/kwcapstone/Service/MemberService.java
Labels: feature

#174 웹소켓 설정 수정
  src/main/java/com/kwcapstone/Config/WebSocketConfig.java
Labels: refactor

#176 웹소켓 설정 변경
  src/main/java/com/kwcapstone/Config/WebSocketConfig.java
Labels: feature

#177 웹소켓 관련 jwt 수정
  src/main/java/com/kwcapstone/Security/JwtRequestFilter.java
Labels: refactor

#179 jwt 로그 추가
  src/main/java/com/kwcapstone/Security/JwtRequestFilter.java
Labels: refactor

#180 jwt 수정
  src/main/java/com/kwcapstone/Security/JwtRequestFilter.java
Labels: refactor

#186 [Refactor] positon 관련 정보도 프롬프트에서 받아오도록 수정 및 추출 코드 추가
  src/main/java/com/kwcapstone/AI/GptService.java
  src/main/java/com/kwcapstone/Service/ConferenceService.java
Labels: refactor

#187 Feat 프로젝트 저장 부분 구현
  .gitignore
  src/main/java/com/kwcapstone/Common/Response/SuccessStatus.java
  src/main/java/com/kwcapstone/Controller/ConferenceController.java
  src/main/java/com/kwcapstone/Domain/Dto/Request/SaveProjectRequestDto.java
  src/main/java/com/kwcapstone/Service/ConferenceService.java
  src/main/java/com/kwcapstone/Service/S3Service.java
  tmp/8A396A889C26B57C47AE7B3D4C83EA908411B8A4/servlet-sessions/SESSIONS.ser
  tmp/script_681314e271d72cd0218ac7fb.txt
Labels: feature

#189 Refactor: 키워드 부분 리턴 수정
  src/main/java/com/kwcapstone/AI/GptService.java
  src/main/java/com/kwcapstone/Domain/Dto/Response/NodeUpdateResponseDto.java
  src/main/java/com/kwcapstone/Service/ConferenceService.java
Labels: refactor

#190 Refactor: 추천 키워드 형식 수정
  src/main/java/com/kwcapstone/AI/GptService.java
Labels: refactor

#194 [Refactor] 비밀번호 초기화 에러 처리 추가하기
  src/main/java/com/kwcapstone/Service/MemberService.java
Labels: refactor
